Rewrite README to encompass recommendations from interviews and the n…
Amsterdam/development-standards pull request #13
Opened 2024-04-26 08:16 UTC by SireeKoolenWijkstra

to encompass recommendations from interviews and the new format for standards

2024-04-29 12:29 UTC, thomasm0 requested changes

2024-04-29 12:29 UTC, thomasm0 commented on docs/general/standardReadMe.md
One request, change filename's camelCase to kebab-case, maybe rename this to `readme-default` (in case we end up with more, for example - `readme-frontend`, `readme-backend` etc.). Other than this everything is good 👍

2024-04-30 09:39 UTC, SireeKoolenWijkstra commented on docs/general/standardReadMe.md
changed it to README-default

2024-05-02 09:23 UTC, thomasm0 approved these changes

2024-05-02 11:08 UTC, merged